### ISSUE TITLE
Create means for assigning full and partial Admin dashboard privileges to individual users

### ISSUE THREAD

**Issue by jim-mcgowan** [redcross/dcsops#166]
I have privileges that permit me to access a full range of configuration options in the Admin dashboard (see below). I believe, currently, I am the only one with full privileges.

<img width="1280" alt="admin dashboard" src="https://user-images.githubusercontent.com/4147733/41372492-1cd2928a-6f13-11e8-9db2-e09b57cd5609.png">

Curiously, when I look at my profile, there is a blank 'position' assigned that signifies that I have these privileges. 

<img width="1280" alt="admin position" src="https://user-images.githubusercontent.com/4147733/41372505-24f28c7c-6f13-11e8-8175-48460c2bd55b.png">

I'd like us to figure out how these privileges can be assigned to other users both universally and, if possible, at a Chapter (Region) level. So, for example, someone in Greater New York can create positions and shifts for their Region but can't do the same for other Regions.

**Incidents**
- Call Logs
- Deployments
- Disasters
- Dispatch Logs
- Events
- Notification Roles
- Number Sequences
- Price List Items
- Report Subscriptions
- Responder Messages
- Scopes
- Territories

**Logistics**
- Vehicles

**Open ID**
- Connect Access Tokens
- Connect Authorizations
- Connect Clients
- Connect Scopes

**Partners**
- Partners

**Roster**
- Cell Carriers
- Chapters
- Counties
- People
- Positions
- Regional Admin
- Roles

**Scheduling**
- Dispatch Configs
- Shift Categories
- Shift Groups
- Shifts

**System**
- Data Filters
- Homepage Links
- Job Logs
- Jobs
- Lookups
- Mot Ds
- Named Queries

**Comment by OhMcGoo** [comment]
Perhaps, the solution to providing Chapter (Regional) level privileges lies in providing access to more of the Admin dashboard configurations items via the DCSOps **Chapter Config** role:
<img width="978" alt="chapter config" src="https://user-images.githubusercontent.com/4147733/41421207-d80209e8-6fbb-11e8-9000-ec70987040f7.png">

**Comment by pjsier** [comment]
@OhMcGoo replying to your comment on the other issue, this should be doable before June 26. It looks like the Chapter Config role is the one that grants full access to all site permissions, but 10 users (including you) seem to have that permission.

It could be a little tricky to add an additional position that goes in between what's currently allowed for Chapter Config site managers and chapter administrators. Would it be alright to allow chapter administrators (it looks like there are 23 currently) to manage more of those items you mentioned, but only inside their chapter?

**Comment by OhMcGoo** [comment]
To your first comment, can you tell me who has Chapter Config permissions? Once I understand who these 10 are, I can better answer your question about giving more permissions to Chapter Admins. Yes, that is the right direction.

**Comment by pjsier** [comment]
@OhMcGoo I emailed you that list, let me know what you think!

**Comment by OhMcGoo** [comment]
Thanks for the list @pjsier. This explains a lot (but still leaves a few questions unanswered). Clearly, John gave site configuration rights to a large number of folks in his home Region. That said, many of these users are no longer affiliated with the Red Cross. I assigned the Chapter Config role to a position I gave to Sara Miller and can see that she can "do all the things." I went one step further and tried to limit her privileges to our Region (Chapter) only by assigning the Role Scope of "2.". That didn't do anything constrain her access. For now, being able to assign the Chapter Config to users I trust in other Regions will be helpful. Still, it would be helpful to add more configuration privileges to the Chapter Admin role. Do you know how this might be done?

**Comment by pjsier** [comment]
@OhMcGoo definitely! Do you want Chapter Admins across the board to be able to manage the items you listed above within their chapter? If so, that should be pretty straightforward to add

**Comment by frankduncan** [comment]
@OhMcGoo Is this still something we want?  There's an open PR from @pjsier that may solve it, and I can add it into staging after the realignment is done for you to look at.

looks like there's still some open questions regarding it.

**Comment by OhMcGoo** [comment]
Now that I understand Capabilities (Roles) better, I think we can handle most privileges that way. I'd still like to learn how my semi-Super Admin privileges are assigned.

**Comment by OhMcGoo** [comment]
@frankduncan:

A regional Admin (aka the **Region Admin** capability, formerly the Chapter Admin role) should have access to only the following Admin console menu items:

**Incidents**

- Events
- Notification Roles

**Logistics**

- Vehicles

**Partners**

- Partners

**Roster**

- Shift Territories
- People
- Positions

**Scheduling**

- Dispatch Configs
- Shift Categories
- Shift Times
- Shifts

**System**

- Homepage Links
- Mot Ds
