### ISSUE TITLE
Calculate time spent responding for each responder and export to Volunteer Connection

### ISSUE THREAD

**Issue by jim-mcgowan** [redcross/dcsops#215]
Time spent responding = DAT Off Scene - Incident Dispatched.

**Comment by kfogel** [comment]
Hunh.  I thought we fixed this?  Will check with @frankduncan.

**Comment by OhMcGoo** [comment]
Pretty sure we didn’t . . . I think we kicked the can down the road on this one due to perceived complexity and cost. I’m now going to unsubscribe from this repo but feel free to reach out to me by e-mail should you have future questions.

**Comment by smeissner** [comment]
Thats good news, its a really important feature for the regions that use it.
