### ISSUE TITLE
When calculating mileage, sum for only ‘Team Lead’ and ‘Responders’

### ISSUE THREAD

**Issue by jim-mcgowan** [redcross/dcsops#259]
When calculating mileage, sum for only responders assigned as ‘Team Lead’ and ‘Responders.’

**Comment by kfogel** [comment]
Estimate: Tiny to Small, but most likely Tiny.

Not ideal for a one-off volunteer, though; requires some contextual knowledge.

**Comment by frankduncan** [comment]
As an added feature, disable this until COVID is over and incidents are being visited personally.

**Comment by frankduncan** [comment]
This actually got fixed, but the commit got lost in a conflict resolution with the unsqueeling during the rails upgrade.
