### ISSUE TITLE
Modify the IIR template

### ISSUE THREAD

**Issue by jim-mcgowan** [redcross/dcsops#260]
Update the DCSOps IIR template to match the current RC standard template.

**Comment by kfogel** [comment]
Tiny to Small, but most likely Tiny.

Not ideal for a one-off volunteer, though; requires some contextual knowledge.

**Comment by jim-mcgowan** [comment]
@frankduncan: Attached are two files to help you modify the IIR creation process. The first (IIR Template Fields) highlights changes to the overall content (orange) and to the "interview" pop-up* specifically (blue). The second (IIR Template Layout) shows what the PDF output should look like. Like the application itself, I have used various weights of Helvetica Neue (Light, Regular, Bold). Please let me know if you'd like to meet to discuss this issue further.

*The pop-up triggered when clicking on most of the field titles in the IIR tab of any incident report

[IIR Template Fields.pdf](https://github.com/redcross/dcsops/files/6030887/IIR.Template.Fields.pdf)
[IIR Template Layout.pdf](https://github.com/redcross/dcsops/files/6030888/IIR.Template.Layout.pdf)

**Comment by jim-mcgowan** [comment]
@frankduncan: Here's the ARC logo for the header.

![american_red_cross_logo_detail](https://user-images.githubusercontent.com/4147733/108886557-b8daec80-75ce-11eb-801f-8e20fa42c068.png)

**Comment by jim-mcgowan** [comment]
@frankduncan: One final note . . . The filenames of IIR PDFs should follow this format: YYYYMMDD_Region Name_Event Type Code_IIR. So the filename of the previously attached IIR would be something like: **20201231_Illinois_MFF_IIR**.

**Comment by jim-mcgowan** [comment]
An improved sample IIR is attached.

[20210101_Illinois_Fire_IIR.pdf](https://github.com/redcross/dcsops/files/6032305/20210101_Illinois_Fire_IIR.pdf)

**Comment by jim-mcgowan** [comment]
Sample template, attached.

[20201231_Illinois_MFF_IIR.pdf](https://github.com/redcross/dcsops/files/6045299/20201231_Illinois_MFF_IIR.pdf)

**Comment by frankduncan** [comment]
And this is what's being generated now:
[20210101_Illinois_MFF_IIR.pdf](https://github.com/redcross/dcsops/files/6055281/20210101_Illinois_MFF_IIR.pdf)

**Comment by jim-mcgowan** [comment]
@frankduncan:

1. Change typeface to Helvetica Neue
2. Increase spacing between lines of text by approximately 10%. If current spacing is 1, Increase to 1.1.

**Comment by frankduncan** [comment]
I have fought with rails and heroku to get it to use other fonts for attachments, and I can't get the pdf to print correctly.  I'm going to create a new, lower priority issue so we don't lose track of this, but I am throwing in the towel for now.
