### ISSUE TITLE
Add to Regional Config and Regional Admin capabilities the ability to change an incident report’s date

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/dcsops#262]
Add to Regional Config and Regional Admin capabilities the ability to change an incident report’s date.

**Comment by kfogel** [comment]
Estimate: Tiny to Small.

When people type in the wrong report date, there's currently no way to fix it.  There should be a way for properly authorized admins to fix it, though.  

Not great for a volunteer, because it involves the permissions system.
