### ISSUE TITLE
Attempting to edit Roles in Roster menu returns blank page, Oh No! (500) error

### ISSUE THREAD

**Issue by jim-mcgowan** [redcross/dcsops#311]
When trying to access Roles via the (Admin >) Roster menu, DCSOps returns a blank page and an Oh No! (500) error.

**Comment by frankduncan** [comment]
I think Roles are replaced by Capabilities.  I can't find any reason they exist now that we changed over.  So I think the correct tack is to remove this page, right?

**Comment by jim-mcgowan** [comment]
Ah, of course. Yes, I think that would be fine.
