### ISSUE TITLE
Create an on-call schedule in DCSOps for the Idaho-Montana Region

### ISSUE THREAD

**Issue by jim-mcgowan** [redcross/dcsops#317]
Similar to the Minnesota / Dakotas On Call Scheduler, create a DCSOps-based on-call schedule for the Idaho-Montana Region. While their current on-call schedule looks like this,

![Idaho and Montana Region Duty Officers](https://user-images.githubusercontent.com/4147733/118882260-9d276f80-b8b9-11eb-885b-1467355ae7fa.png)

show only the name and phone numbers for the currently scheduled **Duty Officer** and **Regional Leadership On Call**.

**Comment by frankduncan** [comment]
This is now at: http://dcsops.org/scheduler/idaho

**Comment by jim-mcgowan** [comment]
For political reasons solely, can you change the URL to http://dcsops.org/scheduler/idaho_montana?

**Comment by jim-mcgowan** [comment]
Catherine Rawsthorne of the Idaho-Montana Region and Clara Walker at NHQ have signed off on the dashboard. I am closing this issue.
